### ISSUE TITLE
Two factor is enabled on this account but not setup in the plugin.

### ISSUE THREAD

**Issue by BinaryShrub** [node-alarm-dot-com/node-alarm-dot-com#20]
I tried using it but get an error with two factor disabled:
```
Error: POST https://www.alarm.com/web/Default.aspx failed: No afg cookie: ASP.NET_SessionId=5zjx5mwfg4n1lc2bbadg0qil; cookieTest=1; twoFactorAuthenticationId=undefined; IsFromNewSite=1; fromASP=; IsFromSeamlessLogin=; login=; ST=; adc_e_loggedInAsSubscriber=1; twoFactorAuthenticationSkipped-14328381=false; BIGipServer~AlarmApplication~Alarm_WEBADC_Alarm_HTTPS=!Zv+qnv3lv+seB+XyKLmNVT65QLIdQIz1d4rIU9aPM57XbCMv1A+zePHGSP/OY6xcr/qdxMepZVr4RCY=
    at node_fetch_1.default.then.catch (/home/jmaneri220/workspace/alarm-dot-com/node_modules/node-alarm-dot-com/dist/index.js:94:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

and when I enable two factor through Alarm.com:
```
Error: GET https://www.alarm.com/web/api/systems/systems/12160720 failed: Two factor is enabled on this account but not setup in the plugin. See the wiki for details
    at get (/home/jmaneri220/workspace/alarm-dot-com/node_modules/node-alarm-dot-com/dist/index.js:463:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by BinaryShrub** [comment]
Looking into the code further it looks like you accept a 3rd param on `login` (btw this isnt documented in the README.md as far as I can tell, might need to be added?)

But even adding my MfaToken as a third param I get the same error as the second one above.

**Comment by BinaryShrub** [comment]
https://github.com/node-alarm-dot-com/homebridge-node-alarm-dot-com/issues/11#issuecomment-789444335 seems like someone else ran into this but it just "resolved?"

**Comment by chase9** [comment]
Hi BinaryShrub,

The login method is documented in the code which will show up in your IDE of choice. You're right that it would be good for me to remove any of the documentation on the readme since I haven't kept it up to date for a number of years now.

As for your other questions, are you calling the library directly, or using the homebridge plugin? Here is an article on the homebridge plugins wiki for using MFA: https://github.com/node-alarm-dot-com/homebridge-node-alarm-dot-com/wiki/Two-Factor-Authentication-Support

**Comment by chase9** [comment]
Closing due to inactivity.

**Comment by DinoChiesa** [comment]
The approach described in the wiki (Referenced [here](https://github.com/node-alarm-dot-com/node-alarm-dot-com/issues/20#issuecomment-1123039197)) still works, for me.
